# Generated by Django 3.2.10 on 2023-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Vehicle_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Vehicle_Model', models.CharField(blank=True, max_length=50, null=True)),
                ('Vehicle_Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
